"""Add is_published is Movie Model

Revision ID: 33736ce37f83
Revises: d910a8aaa83c
Create Date: 2024-07-11 19:23:55.498387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33736ce37f83'
down_revision: Union[str, None] = 'd910a8aaa83c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('is_published', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'is_published')
    # ### end Alembic commands ###
