"""Update Movie Model

Revision ID: 8c958099868f
Revises: bd13e9a081b8
Create Date: 2024-06-24 15:48:22.004438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c958099868f'
down_revision: Union[str, None] = 'bd13e9a081b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('meta_keywords', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'meta_keywords')
    # ### end Alembic commands ###
